Refactor to jlenv-shared.

diff --git a/libexec/jlenv-shared b/libexec/jlenv-shared
--- a/libexec/jlenv-shared
+++ b/libexec/jlenv-shared
@@ -10,6 +10,7 @@
 # Export each variable/function created or modified.
 set -o allexport
 
+unset test_euid
 
 # DESC: Handler for unexpected errors
 # ARGS: $1 (optional): Exit code (defaults to 1)
@@ -26,7 +27,7 @@ function script_trap_err() {
 
     # Validate any provided exit code
     if [[ ${1-} =~ ^[0-9]+$ ]]; then
-        exit_code="$1"
+        exit_code="${1}"
     fi
 
     # Output debug data if in Cron mode
@@ -36,25 +37,26 @@ function script_trap_err() {
             exec 1>&3 2>&4
         fi
 
-        # Print basic debugging information
+        # Restore terminal colours
         printf '%b\n' "$ta_none"
-        printf '***** Abnormal termination of script *****\n'
-        printf 'Script Path:            %s\n' "$script_path"
-        printf 'Script Parameters:      %s\n' "$script_params"
-        printf 'Script Exit Code:       %s\n' "$exit_code"
+        # Print basic debugging information
+        printf 'jlenv:  ***** Abnormal termination of script `*****\n'
+        printf 'jlenv:  Script Path:            %s\n' "$jlenv_path"
+        printf 'jlenv:  Script Parameters:      %s\n' "$jlenv_params"
+        printf 'jlenv:  Script Exit Code:       %s\n' "$exit_code"
 
         # Print the script log if we have it. It's possible we may not if we
         # failed before we even called cron_init(). This can happen if bad
         # parameters were passed to the script so we bailed out very early.
         if [[ -n ${script_output-} ]]; then
-            printf 'Script Output:\n\n%s' "$(cat "$script_output")"
+            printf 'jlenv:  Script Output:\n\n%s' "$(cat "$script_output")"
         else
-            printf 'Script Output:          None (failed before log init)\n'
+            printf 'jlenv:  Script Output:          None (failed before log init)\n'
         fi
     fi
 
     # Exit with failure status
-    exit "$exit_code"
+    exit "${exit_code}"
 }
 
 
@@ -62,7 +64,7 @@ function script_trap_err() {
 # ARGS: None
 # OUTS: None
 function script_trap_exit() {
-    cd "$orig_cwd"
+    cd "${jlenv_orig_cwd:-}"
 
     # Remove Cron mode script log
     if [[ -n ${cron-} && -f ${script_output-} ]]; then
@@ -75,7 +77,7 @@ function script_trap_exit() {
     fi
 
     # Restore terminal colours
-    printf '%b' "$ta_none"
+    printf '%b' "${ta_none:-}"
 }
 
 
@@ -85,43 +87,42 @@ function script_trap_exit() {
 # OUTS: None
 function script_exit() {
     if [[ $# -eq 1 ]]; then
-        printf '%s\n' "$1"
+        printf 'jlenv:  %s\n' "${1}"
         exit 0
     fi
 
     if [[ ${2-} =~ ^[0-9]+$ ]]; then
-        printf '%b\n' "$1"
+        printf 'jlenv:  %b\n' "${1}"
         # If we've been provided a non-zero exit code run the error trap
         if [[ $2 -ne 0 ]]; then
-            script_trap_err "$2"
+            script_trap_err "${2}"
         else
             exit 0
         fi
     fi
 
-    script_exit 'Missing required argument to script_exit()!' 2
+    script_exit "Missing required argument to \$(script_exit)" 2
 }
-
 
 # DESC: Generic script initialisation
 # ARGS: $@ (optional): Arguments provided to the script
-# OUTS: $orig_cwd: The current working directory when the script was run
-#       $script_path: The full path to the script
-#       $script_dir: The directory path of the script
-#       $script_name: The file name of the script
-#       $script_params: The original parameters provided to the script
-#       $ta_none: The ANSI control code to reset all text attributes
-# NOTE: $script_path only contains the path that was used to call the script
+# OUTS: $orig_`cwd: The current working directory when the script was run
+#       $jlenv_path: The full path to the script
+#       $jlenv_dirname: The directory path of the script
+#       $jlenv_name: The file name of the script
+#       $jlenv_params: The original parameters provided to the script
+#       $ta_no`ne: The ANSI control code to reset all text attributes
+# NOTE: $jlenv_path only contains the path that was used to call the script
 #       and will not resolve any symlinks which may be present in the path.
 #       You can use a tool like realpath to obtain the "true" path. The same
-#       caveat applies to both the $script_dir and $script_name variables.
+#       caveat applies to both the $jlenv_dirname and $jlenv_name variables.
 function script_init() {
     # Useful paths
-    readonly orig_cwd="$PWD"
-    readonly script_path="${BASH_SOURCE[1]}"
-    readonly script_dir="$(dirname "$script_path")"
-    readonly script_name="$(basename "$script_path")"
-    readonly script_params="$*"
+    readonly jlenv_orig_cwd="$(pwd -P)"
+    readonly jlenv_path="$(resolve_path "${BASH_SOURCE[0]}")"
+    readonly jlenv_dirname="$(dirname "$jlenv_path")"
+    readonly jlenv_name="$(basename "$jlenv_path")"
+    readonly jlenv_params="$*"
 
     # Important to always set as we use it in the exit handler
     readonly ta_none="$(tput sgr0 2> /dev/null || true)"
@@ -212,13 +213,151 @@ function colour_init() {
 }
 
 
+# DESC: Convert a hex color value to a (nearish) 0-255 color index.
+# ARGS: $1 (required): Hexadecimal value
+# OUTS: 0-255 color index
+# NOTE: The input value requirement is not enforced.
+# 
+#   Conversion   0-255
+# -------------- -----
+# fromhex 002b36   016
+# fromhex 073642   016
+# fromhex 586e75   060
+# fromhex 657b83   066
+# fromhex 839496   102
+# fromhex 93a1a1   109
+# fromhex eee8d5   224
+# fromhex fdf6e3   230
+# fromhex b58900   136
+# fromhex cb4b16   166
+# fromhex dc322f   160
+# fromhex d33682   162
+# fromhex 6c71c4   062
+# fromhex 268bd2   032
+# fromhex 2aa198   036
+# fromhex 859900   100
+script_hex_to_255(){
+    hex=${1#"#"}
+    r=$(printf '0x%0.2s' "$hex")
+    g=$(printf '0x%0.2s' ${hex#??})
+    b=$(printf '0x%0.2s' ${hex#????})
+    printf '%03d' "$(( (r<75?0:(r-35)/40)*6*6 + 
+                       (g<75?0:(g-35)/40)*6   +
+                       (b<75?0:(b-35)/40)     + 16 ))"
+}
+
+# DESC: Initialise colour variables
+# ARGS: None
+# OUTS: Read-only variables with ANSI control codes
+# NOTE: If --no-colour was set the variables will be empty
+#
+#
+# SOLARIZED HEX     0-255 16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
+# --------- ------- ----- ---- -------  ----------- ---------- ----------- -----------
+# base03    #002b36   016  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
+# base02    #073642   016  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
+# base01    #586e75   060 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
+# base00    #657b83   066 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
+# base0     #839496   102 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
+# base1     #93a1a1   109 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
+# base2     #eee8d5   224  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
+# base3     #fdf6e3   230 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99
+# yellow    #b58900   136  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
+# orange    #cb4b16   166  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
+# red       #dc322f   160  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
+# magenta   #d33682   162  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
+# violet    #6c71c4   062 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
+# blue      #268bd2   032  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
+# cyan      #2aa198   036  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
+# green     #859900   100  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60
+
+function colour_init() {
+    if [[ -z ${no_colour-} ]]; then
+        # Text attributes
+        readonly ta_bold="$(tput bold 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly ta_uscore="$(tput smul 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly ta_blink="$(tput blink 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly ta_reverse="$(tput rev 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly ta_conceal="$(tput invis 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+
+        # Foreground codes
+        readonly fg_black="$(tput setaf 16 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_blue="$(tput setaf 32 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_cyan="$(tput setaf 36 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_green="$(tput setaf 100 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_magenta="$(tput setaf 162 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_red="$(tput setaf 160 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_white="$(tput setaf 7 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly fg_yellow="$(tput setaf 136 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+
+        # Background codes
+        readonly bg_black="$(tput setab 16 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_blue="$(tput setab 102 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_cyan="$(tput setab 109 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_green="$(tput setab 60 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_magenta="$(tput setab 62 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_red="$(tput setab 166 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_white="$(tput setab 230 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+        readonly bg_yellow="$(tput setab 66 2> /dev/null || true)"
+        printf '%b' "$ta_none"
+    else
+        # Text attributes
+        readonly ta_bold=''
+        readonly ta_uscore=''
+        readonly ta_blink=''
+        readonly ta_reverse=''
+        readonly ta_conceal=''
+
+        # Foreground codes
+        readonly fg_black=''
+        readonly fg_blue=''
+        readonly fg_cyan=''
+        readonly fg_green=''
+        readonly fg_magenta=''
+        readonly fg_red=''
+        readonly fg_white=''
+        readonly fg_yellow=''
+
+        # Background codes
+        readonly bg_black=''
+        readonly bg_blue=''
+        readonly bg_cyan=''
+        readonly bg_green=''
+        readonly bg_magenta=''
+        readonly bg_red=''
+        readonly bg_white=''
+        readonly bg_yellow=''
+    fi
+}
+
+
 # DESC: Initialise Cron mode
 # ARGS: None
 # OUTS: $script_output: Path to the file stdout & stderr was redirected to
 function cron_init() {
     if [[ -n ${cron-} ]]; then
         # Redirect all output to a temporary file
-        readonly script_output="$(mktemp --tmpdir "$script_name".XXXXX)"
+        readonly script_output="$(mktemp --tmpdir "$jlenv_name".XXXXX)"
         exec 3>&1 4>&2 1>"$script_output" 2>&1
     fi
 }
@@ -234,14 +373,14 @@ function cron_init() {
 function lock_init() {
     local lock_dir
     if [[ $1 = 'system' ]]; then
-        lock_dir="/tmp/$script_name.lock"
+        lock_dir="/tmp/$jlenv_name.lock"
     elif [[ $1 = 'user' ]]; then
-        lock_dir="/tmp/$script_name.$UID.lock"
+        lock_dir="/tmp/$jlenv_name.$UID.lock"
     else
         script_exit 'Missing or invalid argument to lock_init()!' 2
     fi
 
-    if mkdir "$lock_dir" 2> /dev/null; then
+    if mkdir "${lock_dir}" 2> /dev/null; then
         readonly script_lock="$lock_dir"
         verbose_print "Acquired script lock: $script_lock"
     else
@@ -271,9 +410,9 @@ function pretty_print() {
 
     # Print message & reset text attributes
     if [[ -n ${3-} ]]; then
-        printf '%s%b' "$1" "$ta_none"
+        printf 'jlenv:  %s%b' "$1" "$ta_none"
     else
-        printf '%s%b\n' "$1" "$ta_none"
+        printf 'jlenv:  %s%b\n' "$1" "$ta_none"
     fi
 }
 
@@ -348,16 +487,17 @@ function check_binary() {
 # ARGS: $1 (optional): Set to any value to not attempt root access via sudo
 # OUTS: None
 function check_superuser() {
-    local superuser test_euid
+    local superuser
     if [[ $EUID -eq 0 ]]; then
         superuser=true
     elif [[ -z ${1-} ]]; then
         if check_binary sudo; then
-            verbose_print 'Sudo: Updating cached credentials ...'
+            verbose_print 'sudo: Updating cached credentials ...'
             if ! sudo -v; then
-                verbose_print "Sudo: Couldn't acquire credentials ..." \
+                verbose_print "sudo: Couldn't acquire credentials ..." \
                               "${fg_red-}"
             else
+                local test_euid
                 test_euid="$(sudo -H -- "$BASH" -c 'printf "%s" "$EUID"')"
                 if [[ $test_euid -eq 0 ]]; then
                     superuser=true
@@ -385,8 +525,8 @@ function run_as_root() {
         script_exit 'Missing required argument to run_as_root()!' 2
     fi
 
-    local skip_sudo
     if [[ ${1-} =~ ^0$ ]]; then
+        local skip_sudo
         skip_sudo=true
         shift
     fi
@@ -399,5 +539,150 @@ function run_as_root() {
         script_exit "Unable to run requested command as root: $*" 1
     fi
 }
+
+# DESC: Setup the JLENV_DEBUG environment variable.  Default value is no-debug
+#       if not already set. Values:
+#         1: Debug output
+#         0: No-debug output
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_debug() {
+  case ${JLENV_DEBUG:-0} in
+    0) # Disable tracing
+      set +o xtrace          # Do not trace the execution of the script (no-debug)
+      ;;
+    1) # Enable tracing
+      set -o xtrace          # Trace the execution of the script (debug)
+      ;;
+    *) # Disable tracing
+      set +x
+      ;;
+  esac
+}
+
+# DESC: Setup the GNU coreutils readlink
+# ARGS: None.
+# OUTS: None.
+setup_readlink(){
+  readonly READLINK=$(type -p greadlink readlink | head -1)
+  if [ -z "$READLINK" ]; then
+    echo "jlenv: cannot find readlink - are you missing GNU coreutils?" >&2
+    exit 1
+  fi
+}
+
+# DESC: Setup the GNU coreutils realpath
+# ARGS: None.
+# OUTS: None.
+setup_realpath(){
+  readonly REALPATH=$(type -p grealpath realpath | head -1)
+  if [ -z "$REALPATH" ]; then
+    echo "jlenv: cannot find realpath - are you missing GNU coreutils?" >&2
+    exit 1
+  fi
+}
+
+# DESC: Print value of a symbolic link or canonical file name.
+#       Canonicalise by following symlinks in components of the given name
+#       recursively; all components must exist.
+# ARGS: $1 (required): absolute filename
+# OUTS: Resolved path of any link to filename
+# NOTE: Require GNU coreutils' $(readlink). Does NOT resolve symbolic links.
+resolve_link() {
+    command -p "${READLINK}" --canonicalize-existing "$1"
+  }
+
+# DESC: Print value of a folder or canonical file name.
+#       Canonicalise by replacing relative components of the given name 
+#       recursively; all components must exist.
+# ARGS: $1 (required): absolute filename
+# OUTS: Resolved path of any link to filename
+# NOTE: Require GNU coreutils' $(readlink).
+resolve_path() {
+    command -p "${REALPATH}" --no-symlinks --canonicalize-existing "$1"
+  }
+
+# DESC: Setup the JLENV_ROOT environment variable.  Default value is set if not
+#       already set.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_root() {
+  # test if the variable is set and non-empty
+  if [[ "${JLENV_ROOT:-setdefault}" = "setdefault" ]]; then
+    JLENV_ROOT="${HOME}/.jlenv"
+  else
+    JLENV_ROOT="${JLENV_ROOT%/}"
+  fi
+  export JLENV_ROOT
+}
+
+# DESC: Setup the JLENV_DIR environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_dir() {
+  # test if the variable is set and non-empty
+  if [ "${JLENV_DIR:-setdefault}" = "setdefault" ]; then
+    JLENV_DIR="$PWD"
+  else
+    cd "${JLENV_DIR}" 2>/dev/null || script_exit "Cannot change working directory to \$(${JLENV_DIR})" 1
+    JLENV_DIR="$PWD"
+    cd "$OLDPWD"
+  fi
+  export JLENV_DIR
+}
+
+# DESC: Setup the PATH environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_path() {
+  for plugin_bin in "${JLENV_ROOT}/plugins/"*/bin; do
+    PATH="${plugin_bin}:${PATH}"
+  done
+  export PATH="${jlenv_dirname}:${PATH}"
+}
+
+# DESC: Setup the JLENV_HOOK_PATH environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_hook_path() {
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH:-}:${JLENV_ROOT}/jlenv.d"
+  if [ "${jlenv_dirname%/*}" != "$JLENV_ROOT" ]; then
+    # Add jlenv's own `jlenv.d` unless jlenv was cloned to JLENV_ROOT
+    JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${jlenv_dirname%/*}/jlenv.d"
+  fi
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:/usr/local/etc/jlenv.d:/etc/jlenv.d:/usr/lib/jlenv/hooks"
+  for plugin_hook in "${JLENV_ROOT}/plugins/"*/etc/jlenv.d; do
+    JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${plugin_hook}"
+  done
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH#:}"
+  export JLENV_HOOK_PATH
+}
+
+# DESC: Setup debug/verbose output.
+# ARGS: None.
+# OUTS: None.
+verbose_setup() {
+  verbose=true
+  export JLENV_DEBUG=1
+  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
+  set -o xtrace          # Trace the execution of the script (debug)
+}
+
+#####################################################################
+###  Execute
+#####################################################################
+
+# Each time this script is sourced it sets environment variables
+# This is akin to a function script_defaults()
+setup_jlenv_debug
+setup_readlink
+setup_realpath
+script_init "$@"
+setup_jlenv_root
+setup_jlenv_dir
+shopt -s nullglob
+setup_path
+setup_jlenv_hook_path
+shopt -u nullglob
 
 # vim: syntax=sh cc=80 tw=79 ts=4 sw=4 sts=4 et sr
