Add jlenv2 rehash. 3/10 fail.

diff --git a/libexec/jlenv-rehash b/libexec/jlenv-rehash
--- a/libexec/jlenv-rehash
+++ b/libexec/jlenv-rehash
@@ -1,47 +1,4 @@
 #!/usr/bin/env bash
-#
-# Summary: Rehash jlenv shims (run this after installing executables)
-#
-# Usage: jlenv [<opts>] rehash
-#
-# Installs shims for all Julia executables known to jlenv (i.e.,
-# $(~/.jlenv/versions/*/bin/*)). Run this command after you install a new
-# version of Julia, or install a gem that provides executables.
-
-# Import functions shared between jlenv scripts and plugins.
-# Function specific to each jlenv-<command> script are:
-# - script_usage
-# - main "$@" which calls
-#    1. script_init "$@"
-#    2. script_defaults
-#    3. parse_cmds "$@"
-# - $(jlevn_<command>) holds functional logic and is called by $(parse_cmds)
-source jlenv-shared
-
-set -e
-[ -n "$JLENV_DEBUG" ] && set -x
-
-SHIM_PATH="${JLENV_ROOT}/shims"
-PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.jlenv-shim"
-
-# Create the shims directory if it doesn't already exist.
-mkdir -p "$SHIM_PATH"
-
-# Ensure only one instance of jlenv-rehash is running at a time by
-# setting the shell's `noclobber` option and attempting to write to
-# the prototype shim file. If the file already exists, print a warning
-# to stderr and exit with a non-zero status.
-set -o noclobber
-{ echo > "$PROTOTYPE_SHIM_PATH"
-} 2>/dev/null ||
-{ if [ -w "$SHIM_PATH" ]; then
-    echo "jlenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
-  else
-    echo "jlenv: cannot rehash: $SHIM_PATH isn't writable"
-  fi
-  exit 1
-} >&2
-set +o noclobber
 
 # If we were able to obtain a lock, register a trap to clean up the
 # prototype shim when the process exits.
@@ -118,8 +75,6 @@ make_shims() {
   done
 }
 
-registered_shims=" "
-
 # Registers the name of a shim to be generated.
 register_shim() {
   registered_shims="${registered_shims}${1} "
@@ -147,6 +102,38 @@ remove_stale_shims() {
   done
 }
 
+jlenv_rehash()
+## Summary: Rehash jlenv shims (run this after installing executables)
+##
+## Usage: jlenv [<opts>] rehash
+##
+## Installs shims for all Julia executables known to jlenv (i.e.,
+## $(~/.jlenv/versions/*/bin/*)). Run this command after you install a new
+## version of Julia, or install a gem that provides executables.
+{
+SHIM_PATH="${JLENV_ROOT}/shims"
+PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.jlenv-shim"
+
+# Create the shims directory if it doesn't already exist.
+mkdir -p "$SHIM_PATH"
+
+# Ensure only one instance of com_rehash is running at a time by
+# setting the shell's `noclobber` option and attempting to write to
+# the prototype shim file. If the file already exists, print a warning
+# to stderr and exit with a non-zero status.
+set -o noclobber
+{ echo > "$PROTOTYPE_SHIM_PATH"
+} 2>/dev/null ||
+{ if [ -w "$SHIM_PATH" ]; then
+    echo "jlenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
+  else
+    echo "jlenv: cannot rehash: $SHIM_PATH isn't writable"
+  fi
+  exit 1
+} >&2
+set +o noclobber
+
+registered_shims=" "
 shopt -s nullglob
 
 # Create the prototype shim, then register shims for all known
@@ -167,3 +154,4 @@ done
 
 install_registered_shims
 remove_stale_shims
+}
